### ISSUE TITLE
Unable to Launch

### ISSUE THREAD

**Issue by Muhammad-Abubakr** [czlabinger/notion-calendar-electron#5]
System:
![image](https://github.com/czlabinger/notion-calendar-electron/assets/74457014/2f3dbad0-2e26-4546-89de-222c14a57f79)

I am unable to launch the application. Issue may not be related to electron apps as I am also using notion-app-electron and it is working fine. Launching from terminal also does not provide with any output for debugging. 

What can be the issue

**Comment by czlabinger** [comment]
Should be fixed with commit 05288a7. Will update AUR soon

**Comment by czlabinger** [comment]
AUR updated
